name: Emdunn
favicon: null
layout_spectrum: 0.3534967501182109
typography_spectrum: 0.5845854508224875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.06505071953870356
  lightness: 0.9802017065230757
  saturation: 0.9173592231236398
  rhythmicContrast: 0.24158220528624952
purpose: []
